name = "my-worker-test1-<x>-'-name"
type = "javascript"  # or "webpack" depending on your setup
account_id = "468573d665d125bf3f12d12fad6d0edd"
workers_dev = true
compatibility_date = "2024-09-10"

# Specify the main entry point for your worker
main = "./worker.js"  # Change this to the correct path of your worker file

